name: Build and Push Docker Image

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create Docker Secrets
        run: |
          echo "${{ secrets.GEE_CLIENT_EMAIL }}" > /tmp/gee_client_email
          echo "${{ secrets.GEE_PRIVATE_KEY }}" > /tmp/gee_private_key
          echo "${{ secrets.GLOFAS_KEY }}" > /tmp/glofas_key
          echo "${{ secrets.GLOFAS_URL }}" > /tmp/glofas_url
          echo "${{ secrets.MODIS_NRT_TOKEN }}" > /tmp/modis_nrt_token
        shell: bash

      -   name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v3
          with:
              images: t4ds/mcimageprocessing
              tags: |
                  type=semver,pattern={{version}}
                  type=sha,prefix=commit-
                  type=ref,event=branch
                  type=ref,event=pr

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            type=secret,id=GEE_CLIENT_EMAIL,src=/tmp/gee_client_email
            type=secret,id=GEE_PRIVATE_KEY,src=/tmp/gee_private_key
            type=secret,id=GLOFAS_KEY,src=/tmp/glofas_key
            type=secret,id=GLOFAS_URL,src=/tmp/glofas_url
            type=secret,id=MODIS_NRT_TOKEN,src=/tmp/modis_nrt_token
          build-args: |
            LOCALTILESERVER_CLIENT_PREFIX=${{ secrets.LOCALTILESERVER_CLIENT_PREFIX }}

      - name: Cleanup Secrets
        run: rm /tmp/gee_client_email /tmp/gee_private_key /tmp/glofas_key /tmp/glofas_url /tmp/modis_nrt_token
        shell: bash
