name: Create, Encrypt and Upload Config File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create YAML file
        run: |
          cat << EOF > config.yaml
          KEYS:
            GEE:
              client_email: "${{ secrets.GEE_CLIENT_EMAIL }}"
              private_key: "${{ secrets.GEE_PRIVATE_KEY }}"
            GloFas:
              url: "${{ secrets.GLOFAS_URL }}"
              key: "${{ secrets.GLOFAS_KEY }}"
            MODIS_NRT:
              token: "${{ secrets.MODIS_NRT_TOKEN }}"
          EOF

      - name: Encrypt the config file
        run: |
          openssl enc -aes-256-cbc -salt -in config.yaml -out config.enc -k ${{ secrets.ENCRYPTION_KEY }}
          rm config.yaml  # Optionally remove the plaintext file to keep the workspace secure

      - name: Upload encrypted config to secure location
        uses: actions/upload-artifact@v2
        with:
          name: encrypted-config
          path: config.enc

      - name: Cleanup local files
        run: rm config.enc
