name: Build, Encrypt and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Create YAML file
        run: |
          cat << EOF > config.yaml
          KEYS:
            GEE:
              client_email: "${{ secrets.GEE_CLIENT_EMAIL }}"
              private_key: "${{ secrets.GEE_PRIVATE_KEY }}"
            GloFas:
              url: "${{ secrets.GLOFAS_URL }}"
              key: "${{ secrets.GLOFAS_KEY }}"
            MODIS_NRT:
              token: "${{ secrets.MODIS_NRT_TOKEN }}"
          EOF

      - name: Create directory for config
        run: mkdir -p mcimageprocessing/config

      - name: Encrypt the config file
        run: |
          openssl enc -aes-256-cbc -salt -in config.yaml -out mcimageprocessing/config/config.enc -k ${{ secrets.ENCRYPTION_KEY }}
          rm config.yaml

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            t4ds/mcimageprocessing:${{ github.sha }}
            t4ds/mcimageprocessing:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Commit and Push Encrypted File
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add mcimageprocessing/config/config.enc
          git commit -m "Add encrypted config file"
          git push

      - name: Cleanup
        run: rm mcimageprocessing/config/config.enc
