name: Build, Encrypt and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create YAML file
        run: |
          cat << EOF > config.yaml
          KEYS:
            GEE:
              client_email: "${{ secrets.GEE_CLIENT_EMAIL }}"
              private_key: "${{ secrets.GEE_PRIVATE_KEY }}"
            GloFas:
              url: "${{ secrets.GLOFAS_URL }}"
              key: "${{ secrets.GLOFAS_KEY }}"
            MODIS_NRT:
              token: "${{ secrets.MODIS_NRT_TOKEN }}"
          EOF

      - name: Encrypt the config file
        run: |
          openssl enc -aes-256-cbc -salt -in config.yaml -out config.enc -k ${{ secrets.ENCRYPTION_KEY }}
          rm config.yaml  # Remove plaintext file

      - name: Build Docker image
        run: |
          docker build -t t4ds/mcimageprocessing:${{ github.sha }} .
        env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push t4ds/mcimageprocessing:${{ github.sha }}

      - name: Cleanup
        run: rm config.enc
